### ISSUE TITLE
Issue 1

### ISSUE THREAD

**Issue by crisketm** [crisketm/self-xdsd-testground#1]
Issue 1

**Comment by charlesmike** [comment]
@crisketm thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@crisketm2 this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-09T15:21:03.818193``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@crisketm2 Don't forget to close this ticket before the deadline (2021-01-09T15:21:03). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@crisketm2 Looks like you've missed the task deadline (2021-01-09T15:21:03). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-19T21:06:39.387407``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by criske** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister 

@criske ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by crisketm** [comment]
@charlesmike register

**Comment by charlesmike** [comment]
> @charlesmike register

@crisketm I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by charlesmike** [comment]
@crisketm2 this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-21T09:46:00.902526``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@crisketm2 Don't forget to close this ticket before the deadline (2021-01-21T09:46). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@crisketm2 Looks like you've missed the task deadline (2021-01-21T09:46). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-31T15:06:16.470120``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by crisketm** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@crisketm ok, I've removed this task from scope. I'm not managing it anymore.
